### ISSUE TITLE
Add Support for Aqara MCCGQ11LM contact sensor

### ISSUE THREAD

**Issue by blitz79** [varzac/EdgeDrivers#7]
Hopefully it is easy by extending lumi.sensor_magnet and add lumi.sensor_magnet.aq2
Thank you

**Comment by veonua** [comment]
already implemented by Yakov
https://community.smartthings.com/t/what-happened-to-my-automations/232633

**Comment by blitz79** [comment]
Sorry. I think you posted the wrong link? I believe I did try Yakov's drivers .. ones containing this string "[YG]" and it did not work with this aqara sensor. I was not sure if they were going to fix and i could not find their git to fork and attempt myself.

However, I did fork from your git and replaced the magnet_sensor to magnet_sensor.aq2 and it seem to be working so far. Just open/close. The battery and temp are not working which is okay with me.

**Comment by blitz79** [comment]
Yakov mentioned that his drivers should work for this. I am not sure why it did not work the first time. Now it works perfect. Not for future readers. Takes one hour or so to get RSSI/LQI/battery to get updated after link.
https://community.smartthings.com/t/st-edge-beta-xiaomi-aqara-zigbee-door-sensor-driver/234709/49
